services:
  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: api_HairFlow
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-hairflow:
    build: .    
    container_name: 'backend-hairflow'
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data:
