services:
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  # Variável de ambiente definida no arquivo .env
      MYSQL_DATABASE: api_HairFlow  # Correção aqui, sem o :v1
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: api_hairflow:v2.0
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Certifique-se de que essa variável está no .env
      DATABASE_USERNAME: ${DATABASE_USERNAME}  # Certifique-se de que essa variável está no .env
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}  # Certifique-se de que essa variável está no .env
      JWT_SECRET: ${JWT_SECRET}  # Certifique-se de que essa variável está no .env
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data:
