services:  
  hairflow-db:
    image: postgres:12.4-alpine
    container_name: hairflow-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend-hairflow:
    build: .    
    container_name: 'backend-hairflow'
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      hairflow-db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local

networks:
  app-tier:
    driver: bridge